config/routes.rb
OneBS::Application.routes.draw do

  get 'home/update_badge', :as => 'update_badge'

  get "medias/show"

  get "medias/delete"

  match "/how_it_works", :to => "home#how_it_works"
  match "/participate", :to => "home#participate"
  match "/badges", :to => "home#badges"
  match "/about", :to => "home#about"
  match "/charities", :to => "charities#index"
  match "/contact", :to => "home#contact"
  match "/our_story", :to => "home#our_story"
  match "/ccc", :to => "home#ccc"
  match "/top_ten_reasons", :to => "home#top_ten_reasons"
  match "/share_contest", :to => "home#share_contest"
  match "/brand", :to => "home#brand"
  match "/client_spotlight", :to => "home#client_spotlight"
  match "/client_slight", :to => "home#client_slight"
  match "/faq", :to => "home#faq"
  match "/calendar", :to => "home#calendar"
  match "/impact", :to => "home#impact"
  match "/socialize", :to => "home#socialize"
  match "/channel", :to => "home#channel"
  match "/facility", :to => "home#facility"
  match "/customers", :to => "home#customers"
  match "/manifesto", :to => "home#manifesto"
  match "/download_thank_you_card", :to => "home#download_thank_you_card"
  match "/print_thank_you_card", :to => "home#print_thank_you_card"

  devise_for :admins, :controllers => {
      :sessions => "admins/sessions"
  }

  devise_scope :admin do
    get "sign_in" => "admins/sessions#new"
    get "sign_out" => "admins/sessions#destroy"
  end

    namespace :admins do
      resources :orders
      resources :site_events  do
        get :subscribers, :on => :collection
        put :approve, :on => :member
      end
      resource :cost_matrix
      resources :banners
      resources :client_spotlights
      resources :questions
      resources :questions_categories
      resources :posts
      resources :charities do
        member do
          put :approve
        end
        collection do
          get :image_form
          get :pending
        end
    end
    resources :charity_categories
    resources :suggested_charities
    resources :references
    resources :pages
    resources :style_categories
    resources :style_sub_categories
    resources :styles
    resources :shirt_colors
    resources :color_groups
    resources :contests
    resources :customers
    resources :settings
  end

  resources :home do
    collection do
      get :how_it_works, :customers, :participate, :contact, :about, :facility, :download, :calculate_value, :calculated_value_popup, :top_ten_reasons, :share_contest, :thank_you,
          :view_all_charities, :get_questions, :socialize, :channel, :download_thank_you_card, :print_thank_you_card
      post :send_email
      post :calculate_impact
    end
  end

  resource :events do
    post :subscribers, :on => :collection
    get :thanks, :on => :member
  end

  resources :contests  do
    get :vote, :on => :member
  end

  resources :charities do
    collection do
      get :get_charities, :sort_charities, :details,:request_quote, :image_form, :suggest_charity, :go_to_charity, :count_share
      post :search_charities, :add_charity
    end
  end

  resources :orders do
    collection do
      get :quick_quote
      get :calculate
      get :thankyou
    end
  end

  match "/:id", :to => "charities#show"
  match "/contests/:id", :to => "contests#show"

  root :to => 'home#index'

end

app/models/color_group.rb
class ColorGroup < ActiveRecord::Base
  attr_accessible :name

  has_many :shirt_colors
  has_many :style
end

app/controllers/admins/color_groups_controller.rb
class Admins::ColorGroupsController < Admins::HomeController
    # GET /admins/charity_categories
    # GET /admins/charity_categories.json
    def index
      @color_groups = ColorGroup.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @color_groups }
      end
    end

    # GET /admins/charity_categories/new
    # GET /admins/charity_categories/new.json
    def new
      @color_group = ColorGroup.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @color_group }
      end
    end

    # GET /admins/charity_categories/1/edit
    def edit
      @color_group = ColorGroup.find(params[:id])
    end

    # POST /admins/charity_categories
    # POST /admins/charity_categories.json
    def create
      @color_group = ColorGroup.new(params[:color_group])

      respond_to do |format|
        if @color_group.save
          format.html { redirect_to admins_color_groups_url, notice: 'Color Group was successfully created.' }
          format.json { render json: @color_group, status: :created, location: @color_group }
        else
          format.html { render action: "new" }
          format.json { render json: @color_group.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /admins/charity_categories/1
    # PUT /admins/charity_categories/1.json
    def update
      @color_group = ColorGroup.find(params[:id])

      respond_to do |format|
        if @color_group.update_attributes(params[:color_group])
          format.html { redirect_to admins_color_groups_url, notice: 'Group Color was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @color_group.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admins/charity_categories/1
    # DELETE /admins/charity_categories/1.json
    def destroy
      @color_group = ColorGroup.find(params[:id])
      @color_group.destroy

      respond_to do |format|
        format.html { redirect_to admins_color_groups_url }
        format.json { head :no_content }
      end
    end
end

app/helpers/admins/color_groups_helper.rb
module Admins::ColorGroupsHelper
end

app/views/admins/color_groups/_form.html.haml
= form_for([:admins, @color_group]) do |f|
  - if @color_group.errors.any?
    #error_explanation
      %h2
        = pluralize(@color_group.errors.count, "error")
        prohibited this style category from being
        saved:
      %ul
        - @color_group.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit "Save", :class => "smallBtn"

app/views/admins/color_groups/edit.html.haml
%h1 Edit Color Group
= render :partial => 'form'
%div{:style => "float: left;width:100%;"}
  = link_to 'Back', admins_color_groups_path

app/views/admins/color_groups/index.html.haml
.row
  .span6
    %h2 Color Groups
  .span5
    = link_to 'New Color Group', new_admins_color_group_path, class:"btn btn-primary new_btn"
%table.table-striped.table.table-bordered
  %tr
    %th Name
    %th
  - @color_groups.each do |color_group|
    %tr
      %td= color_group.name
      %td
        = link_to '<i class="icon-pencil"></i>'.html_safe, edit_admins_color_group_path(color_group)
        = link_to '<i class="icon-remove"></i>'.html_safe, admins_color_group_path(color_group), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admins/color_groups/new.html.haml
%h1 New Color Group
- url = admins_color_groups_path
= render :partial => 'form', :locals => { :url => url }
%div{:style => "float: left;width:100%;"}
  = link_to 'Back', admins_color_groups_path