config/routes.rb
OneBS::Application.routes.draw do

  get 'home/update_badge', :as => 'update_badge'

  get "medias/show"

  get "medias/delete"

  match "/how_it_works", :to => "home#how_it_works"
  match "/participate", :to => "home#participate"
  match "/badges", :to => "home#badges"
  match "/about", :to => "home#about"
  match "/charities", :to => "charities#index"
  match "/contact", :to => "home#contact"
  match "/our_story", :to => "home#our_story"
  match "/ccc", :to => "home#ccc"
  match "/top_ten_reasons", :to => "home#top_ten_reasons"
  match "/share_contest", :to => "home#share_contest"
  match "/brand", :to => "home#brand"
  match "/client_spotlight", :to => "home#client_spotlight"
  match "/client_slight", :to => "home#client_slight"
  match "/faq", :to => "home#faq"
  match "/calendar", :to => "home#calendar"
  match "/impact", :to => "home#impact"
  match "/socialize", :to => "home#socialize"
  match "/channel", :to => "home#channel"
  match "/facility", :to => "home#facility"
  match "/customers", :to => "home#customers"
  match "/manifesto", :to => "home#manifesto"
  match "/download_thank_you_card", :to => "home#download_thank_you_card"
  match "/print_thank_you_card", :to => "home#print_thank_you_card"

  devise_for :admins, :controllers => {
      :sessions => "admins/sessions"
  }

  devise_scope :admin do
    get "sign_in" => "admins/sessions#new"
    get "sign_out" => "admins/sessions#destroy"
  end

    namespace :admins do
      resources :orders
      resources :site_events  do
        get :subscribers, :on => :collection
        put :approve, :on => :member
      end
      resource :cost_matrix
      resources :banners
      resources :client_spotlights
      resources :questions
      resources :questions_categories
      resources :posts
      resources :charities do
        member do
          put :approve
        end
        collection do
          get :image_form
          get :pending
        end
    end
    resources :charity_categories
    resources :suggested_charities
    resources :references
    resources :pages
    resources :style_categories
    resources :style_sub_categories
    resources :styles
    resources :shirt_colors
    resources :color_groups
    resources :contests
    resources :customers
    resources :settings
  end

  resources :home do
    collection do
      get :how_it_works, :customers, :participate, :contact, :about, :facility, :download, :calculate_value, :calculated_value_popup, :top_ten_reasons, :share_contest, :thank_you,
          :view_all_charities, :get_questions, :socialize, :channel, :download_thank_you_card, :print_thank_you_card
      post :send_email
      post :calculate_impact
    end
  end

  resource :events do
    post :subscribers, :on => :collection
    get :thanks, :on => :member
  end

  resources :contests  do
    get :vote, :on => :member
  end

  resources :charities do
    collection do
      get :get_charities, :sort_charities, :details,:request_quote, :image_form, :suggest_charity, :go_to_charity, :count_share
      post :search_charities, :add_charity
    end
  end

  resources :orders do
    collection do
      get :quick_quote
      get :calculate
      get :thankyou
    end
  end

  match "/:id", :to => "charities#show"
  match "/contests/:id", :to => "contests#show"

  root :to => 'home#index'

end

app/views/admins/pages/_form.html.haml
= form_for(@page, :url => url) do |f|
  - if @page.errors.any?
    #error_explanation
      %h2
        = pluralize(@page.errors.count, "error")
        prohibited this page from being saved:
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg
  %h1= @page.page_name
  .field
    = f.label :header_content
    = f.text_area :header_content
    = f.label :page_content
    = f.text_area :page_content
  .span2.offset4
    = f.submit "Save", :class => "btn btn-primary",:style=>"width:150px"
:javascript
  tinyMCE.init({
      mode: 'textareas',
      theme: 'advanced'
  });

app/views/admins/pages/edit.html.haml
.row
  .span12{style:"text-align:center"}
    %h2 Editing page
- url = admins_page_path(@page)
= render :partial => 'form', :locals => { :url => url }

app/views/admins/pages/index.html.haml
.row
  .span6
    %h2 Listing pages
  .span5
    =# link_to 'New Page', new_admins_page_path, class: "btn btn-primary new_btn"
%table.table-striped.table.table-bordered
  %tr
    %th
    %th
  - @pages.each do |page|
    %tr
      %td
        = link_to page.page_name , admins_page_path(page)
      %td
        = link_to '<i class="icon-pencil"></i>'.html_safe, edit_admins_page_path(page)

app/views/admins/pages/new.html.haml
.row
  .span12{style:"text-align:center"}
    %h2 New page
- url = admins_page_path(@page)
= render :partial => 'form', :locals => { :url => url }

app/views/admins/pages/show.html.haml
%p#notice= notice
- unless @page.blank?
  %h1= @page.page_name.capitalize
  %p
    = raw(@page.header_content)
  %p
    = raw(@page.page_content)
= link_to 'Edit', edit_admins_page_path(@page)
|
\#{link_to 'Back', admins_pages_path}