config/routes.rb
OneBS::Application.routes.draw do

  get 'home/update_badge', :as => 'update_badge'

  get "medias/show"

  get "medias/delete"

  match "/how_it_works", :to => "home#how_it_works"
  match "/participate", :to => "home#participate"
  match "/badges", :to => "home#badges"
  match "/about", :to => "home#about"
  match "/charities", :to => "charities#index"
  match "/contact", :to => "home#contact"
  match "/our_story", :to => "home#our_story"
  match "/ccc", :to => "home#ccc"
  match "/top_ten_reasons", :to => "home#top_ten_reasons"
  match "/share_contest", :to => "home#share_contest"
  match "/brand", :to => "home#brand"
  match "/client_spotlight", :to => "home#client_spotlight"
  match "/client_slight", :to => "home#client_slight"
  match "/faq", :to => "home#faq"
  match "/calendar", :to => "home#calendar"
  match "/impact", :to => "home#impact"
  match "/socialize", :to => "home#socialize"
  match "/channel", :to => "home#channel"
  match "/facility", :to => "home#facility"
  match "/customers", :to => "home#customers"
  match "/manifesto", :to => "home#manifesto"
  match "/download_thank_you_card", :to => "home#download_thank_you_card"
  match "/print_thank_you_card", :to => "home#print_thank_you_card"

  devise_for :admins, :controllers => {
      :sessions => "admins/sessions"
  }

  devise_scope :admin do
    get "sign_in" => "admins/sessions#new"
    get "sign_out" => "admins/sessions#destroy"
  end

    namespace :admins do
      resources :orders
      resources :site_events  do
        get :subscribers, :on => :collection
        put :approve, :on => :member
      end
      resource :cost_matrix
      resources :banners
      resources :client_spotlights
      resources :questions
      resources :questions_categories
      resources :posts
      resources :charities do
        member do
          put :approve
        end
        collection do
          get :image_form
          get :pending
        end
    end
    resources :charity_categories
    resources :suggested_charities
    resources :references
    resources :pages
    resources :style_categories
    resources :style_sub_categories
    resources :styles
    resources :shirt_colors
    resources :color_groups
    resources :contests
    resources :customers
    resources :settings
  end

  resources :home do
    collection do
      get :how_it_works, :customers, :participate, :contact, :about, :facility, :download, :calculate_value, :calculated_value_popup, :top_ten_reasons, :share_contest, :thank_you,
          :view_all_charities, :get_questions, :socialize, :channel, :download_thank_you_card, :print_thank_you_card
      post :send_email
      post :calculate_impact
    end
  end

  resource :events do
    post :subscribers, :on => :collection
    get :thanks, :on => :member
  end

  resources :contests  do
    get :vote, :on => :member
  end

  resources :charities do
    collection do
      get :get_charities, :sort_charities, :details,:request_quote, :image_form, :suggest_charity, :go_to_charity, :count_share
      post :search_charities, :add_charity
    end
  end

  resources :orders do
    collection do
      get :quick_quote
      get :calculate
      get :thankyou
    end
  end

  match "/:id", :to => "charities#show"
  match "/contests/:id", :to => "contests#show"

  root :to => 'home#index'

end

app/views/layouts/admin/_footer.html.haml
.footer
  %p © 2013 One Billien Shirts Pty Ltd. All rights reserved

app/views/layouts/admin/_header.html.haml
.topBanner
  .logo
    = image_tag("logo_admin.png")
  - if admin_signed_in?
    .topRightNav
      .topLinks
        %span.gray
        = current_admin.email
        | #{link_to "Sign Out", sign_out_path}

app/views/layouts/admin/_links.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar.collapsed{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =#link_to "OneBS Admin" ,admins_banners_path
      #main-menu.nav-collapse.collapse{:style => "height: 0px;"}
        %ul#main-menu-left.nav
          %li.active
            =link_to "Orders" , admins_orders_path
          %li
            =link_to "Cost Matrix" , admins_cost_matrix_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Colors
              %b.caret
            %ul#swatch-menu.dropdown-menu
              %li
                =link_to "Color Group" , admins_color_groups_path
              %li
                =link_to "Colors" , admins_shirt_colors_path
          %li
            =link_to "Banners" , admins_banners_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Charities
              %b.caret
            %ul#swatch-menu.dropdown-menu
              %li
                =link_to "Charities" , admins_charities_path
              %li
                =link_to "Pending Approval" , pending_admins_charities_path
              %li
                =link_to "New Charity" , new_admins_charity_path
              %li.divider
              %li
                =link_to "Categories" , admins_charity_categories_path
              %li
                =link_to "New Category" , new_admins_charity_category_path
              %li.divider
              %li
                =link_to "Suggested" , admins_suggested_charities_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Events
              %b.caret
            %ul#swatch-menu.dropdown-menu
              %li
                =link_to "Pending Events" , admins_site_events_path
              %li
                =link_to "Event Subscribers" , subscribers_admins_site_events_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Shirt Styles
              %b.caret
            %ul#swatch-menu.dropdown-menu
              %li
                =link_to "Style Categories" , admins_style_categories_path
              %li
                =link_to "Style Sub Categories" , admins_style_sub_categories_path
              %li
                =link_to "Styles" , admins_styles_path
          %li
            =link_to "References" , admins_references_path 
          %li
            =link_to "Static Pages" , admins_pages_path
          %li
            =link_to "Image Upload" , admins_posts_path
          %li
            =link_to "Client Spotlights" , admins_client_spotlights_path
          %li
            =link_to "Contests" , admins_contests_path
          %li
            =link_to "CTC" , admins_customers_path
          %li
            =link_to "Settings" , admins_settings_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              FAQs
              %b.caret
            %ul#swatch-menu.dropdown-menu
              %li
                =link_to "Categories" , admins_questions_categories_path
              %li
                =link_to "New Category" , new_admins_questions_category_path
              %li.divider
              %li
                =link_to "Questions" , admins_questions_path
              %li
                =link_to "New Question" , new_admins_question_path