config/routes.rb
OneBS::Application.routes.draw do

  get 'home/update_badge', :as => 'update_badge'

  get "medias/show"

  get "medias/delete"

  match "/how_it_works", :to => "home#how_it_works"
  match "/participate", :to => "home#participate"
  match "/badges", :to => "home#badges"
  match "/about", :to => "home#about"
  match "/charities", :to => "charities#index"
  match "/contact", :to => "home#contact"
  match "/our_story", :to => "home#our_story"
  match "/ccc", :to => "home#ccc"
  match "/top_ten_reasons", :to => "home#top_ten_reasons"
  match "/share_contest", :to => "home#share_contest"
  match "/brand", :to => "home#brand"
  match "/client_spotlight", :to => "home#client_spotlight"
  match "/client_slight", :to => "home#client_slight"
  match "/faq", :to => "home#faq"
  match "/calendar", :to => "home#calendar"
  match "/impact", :to => "home#impact"
  match "/socialize", :to => "home#socialize"
  match "/channel", :to => "home#channel"
  match "/facility", :to => "home#facility"
  match "/customers", :to => "home#customers"
  match "/manifesto", :to => "home#manifesto"
  match "/download_thank_you_card", :to => "home#download_thank_you_card"
  match "/print_thank_you_card", :to => "home#print_thank_you_card"

  devise_for :admins, :controllers => {
      :sessions => "admins/sessions"
  }

  devise_scope :admin do
    get "sign_in" => "admins/sessions#new"
    get "sign_out" => "admins/sessions#destroy"
  end

    namespace :admins do
      resources :orders
      resources :site_events  do
        get :subscribers, :on => :collection
        put :approve, :on => :member
      end
      resource :cost_matrix
      resources :banners
      resources :client_spotlights
      resources :questions
      resources :questions_categories
      resources :posts
      resources :charities do
        member do
          put :approve
        end
        collection do
          get :image_form
          get :pending
        end
    end
    resources :charity_categories
    resources :suggested_charities
    resources :references
    resources :pages
    resources :style_categories
    resources :style_sub_categories
    resources :styles
    resources :shirt_colors
    resources :color_groups
    resources :contests
    resources :customers
    resources :settings
  end

  resources :home do
    collection do
      get :how_it_works, :customers, :participate, :contact, :about, :facility, :download, :calculate_value, :calculated_value_popup, :top_ten_reasons, :share_contest, :thank_you,
          :view_all_charities, :get_questions, :socialize, :channel, :download_thank_you_card, :print_thank_you_card
      post :send_email
      post :calculate_impact
    end
  end

  resource :events do
    post :subscribers, :on => :collection
    get :thanks, :on => :member
  end

  resources :contests  do
    get :vote, :on => :member
  end

  resources :charities do
    collection do
      get :get_charities, :sort_charities, :details,:request_quote, :image_form, :suggest_charity, :go_to_charity, :count_share
      post :search_charities, :add_charity
    end
  end

  resources :orders do
    collection do
      get :quick_quote
      get :calculate
      get :thankyou
    end
  end

  match "/:id", :to => "charities#show"
  match "/contests/:id", :to => "contests#show"

  root :to => 'home#index'

end

app/models/questions_category.rb
class QuestionsCategory < ActiveRecord::Base
  has_many :questions
  attr_accessible :category
end

app/controllers/admins/questions_categories_controller.rb
class Admins::QuestionsCategoriesController < Admins::HomeController
  # GET /questions_categories
  # GET /questions_categories.json
  def index
    @questions_categories = QuestionsCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions_categories }
    end
  end

  # GET /questions_categories/1
  # GET /questions_categories/1.json
  def show
    @questions_category = QuestionsCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @questions_category }
    end
  end

  # GET /questions_categories/new
  # GET /questions_categories/new.json
  def new
    @questions_category = QuestionsCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @questions_category }
    end
  end

  # GET /questions_categories/1/edit
  def edit
    @questions_category = QuestionsCategory.find(params[:id])
  end

  # POST /questions_categories
  # POST /questions_categories.json
  def create
    @questions_category = QuestionsCategory.new(params[:questions_category])

    respond_to do |format|
      if @questions_category.save
        format.html {redirect_to admins_questions_categories_url, notice: 'Questions category was successfully created.' }
        format.json { render json: @questions_category, status: :created, location: @questions_category }
      else
        format.html { render action: "new" }
        format.json { render json: @questions_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions_categories/1
  # PUT /questions_categories/1.json
  def update
    @questions_category = QuestionsCategory.find(params[:id])

    respond_to do |format|
      if @questions_category.update_attributes(params[:questions_category])
        format.html { redirect_to admins_questions_categories_path, notice: 'Questions category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @questions_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions_categories/1
  # DELETE /questions_categories/1.json
  def destroy
    @questions_category = QuestionsCategory.find(params[:id])
    @questions_category.destroy

    respond_to do |format|
      format.html { redirect_to admins_questions_categories_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_categories_helper.rb
module QuestionsCategoriesHelper
end

app/views/admins/questions_categories/_form.html.haml
= form_for(@questions_category, :url => url, :html => {:class=>"form-inline"}) do |f|
  - if @questions_category.errors.any?
    #error_explanation
      %h2
        = pluralize(@questions_category.errors.count, "error")
        prohibited this questions_category from being saved:
      %ul
        - @questions_category.errors.full_messages.each do |msg|
          %li= msg
  .field{style:"padding-left:40px"}
    = f.label :category, class:"control-label"
    = f.text_field :category
    = f.submit "Save", :class => "btn btn-primary",:style=>"width:150px"

app/views/admins/questions_categories/edit.html.haml
.row
  .span12{style:"text-align:center"}
    %h2 Editing questions_category
- url = admins_questions_category_path(@questions_category)
= render :partial => 'form', :locals => {:url => url}

app/views/admins/questions_categories/index.html.haml
.row
  .span6
    %h2 FAQ Categories
  .span5
    = link_to 'New FAQ Category', new_admins_questions_category_path, class: "btn btn-primary new_btn"
%table.table-striped.table.table-bordered
  %tr
    %th Name
    %th
  - @questions_categories.each do |questions_category|
    %tr
      %td= questions_category.category
      %td
        =link_to '<i class="icon-pencil"></i>'.html_safe, edit_admins_questions_category_path(questions_category)
        =link_to '<i class="icon-remove"></i>'.html_safe, admins_questions_category_path(questions_category), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admins/questions_categories/new.html.haml
.row
  .span12{style:"text-align:center"}
    %h2 New Questions Category
- url = admins_questions_categories_path(@questions_categories)
= render :partial => 'form', :locals => {:url => url}

app/views/admins/questions_categories/show.html.haml
%p#notice= notice
%p
  %b Category:
  = @questions_category.category
= link_to 'Edit', edit_questions_category_path(@questions_category)
|
\#{link_to 'Back', questions_categories_path}